destoy changes

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -54,8 +54,16 @@ jobs:
       run: terraform init
       working-directory: ./environments/dev
 
-    - name: Terraform Plan
-      run: terraform plan
+    - name: Terraform Plan (Apply or Destroy)
+      run: |
+        if [ "${{ github.event.inputs.action }}" = "apply" ]; then
+          terraform plan
+        elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
+          terraform plan -destroy
+        else
+          echo "Invalid action input: ${{ github.event.inputs.action }}"
+          exit 1
+        fi
       working-directory: ./environments/dev
 
     - name: Terraform Apply or Destroy
